### ISSUE TITLE
wallet address with etp balance not shown

### ISSUE THREAD

**Issue by cryptickt** [mvs-org/lightwallet#100]
Hello all, Ive been experiencing issues with being locked out of my metaverse wallet, I created this wallet in Oct 2017, made my deposits and froze all my ETP.  Since downloading the wallet I have been able to access the wallet and create transactions without any issues, and was able to access my wallet as early as 3 weeks ago.  However today I tried to login and it gives me a reading "invalid login credentials" but these are the EXACT user name and password Ive been using to access the wallet.  I tried the troubleshooting as disclosed in the wallet manual pdf, but still no luck to access wallet. I went to mvs.org and decided to try the light wallet https://www.myetpwallet.com, went to "create files from backup words" a file was created and I was able to successfully login, HOWEVER there are ZERO transactions in the history and all address balances is ZERO. My wallet address that the etp was deposited to and "frozen" isnt even in here. How is this possible? This is the same 24 word mnemonic backup I received when creating the initial wallet back in October 2017.  Im extremely puzzled and worried that I will not be able to access the etp when they become unfrozen, as the wallet address that contains the etp is NOT reflecting, and yes I have synced and resynced and the blockchain is up to date.  Can anyone here please help me figure this out.

**Comment by LaurentSalou** [comment]
#103 will help on this issue. It will check that all the words types are indeed in the list of words

**Comment by canguruhh** [comment]
close issue because no response. also this issue is more related to the fullnode that created the wallet.
