### ISSUE TITLE
Portfolio is empty on mobile

### ISSUE THREAD

**Issue by menhack92** [mvs-org/lightwallet#111]
Portfolio is empty on mobile
![photo_2018-04-28_13-28-23](https://user-images.githubusercontent.com/29656156/39395513-21c10618-4ae8-11e8-828b-92e964cb155f.jpg)

**Comment by canguruhh** [comment]
cant reproduce. please try again or see if you can open app.myetwallet.com in your browser

**Comment by menhack92** [comment]
On browser portflio is empty too
--
Отправлено из myMail для Android воскресенье, 29 апреля 2018г., 00:58 +03:00 от Sven  notifications@github.com :

**Comment by canguruhh** [comment]
anyone else to reproduce the issue? it works for me on all environments

**Comment by menhack92** [comment]
No, problem is actual
--
Отправлено из myMail для Android четверг, 17 мая 2018г., 11:23 +03:00 от Attick  notifications@github.com :

**Comment by Attick** [comment]
There is support or just people who has problem talk each other?

**Comment by menhack92** [comment]
I am only person, whohas this problem
--
Отправлено из myMail для Android четверг, 17 мая 2018г., 11:30 +03:00 от Attick  notifications@github.com :

**Comment by canguruhh** [comment]
Still I cant reproduce the problem on our test devices

**Comment by canguruhh** [comment]
The icon on the top right corner indicates that the app cant connect to the lightwallet servers

**Comment by canguruhh** [comment]
Try to open the wallet from your phones browser

**Comment by menhack92** [comment]
I have the same result via browser
--
Отправлено из myMail для Android четверг, 17 мая 2018г., 12:35 +03:00 от Sven  notifications@github.com :

**Comment by canguruhh** [comment]
Have you tried to use a different ip address?

**Comment by Attick** [comment]
no, ip was the same

**Comment by canguruhh** [comment]
Problem still existing?
