### ISSUE TITLE
Have problem with withdrawal from myetpwallet

### ISSUE THREAD

**Issue by Attick** [mvs-org/lightwallet#116]
When I try to withdrawal etp from my wallet i recive messege - "Please note currently each account can only broadcast 1 transaction per block"
![photo_2018-05-17_09-17-19](https://user-images.githubusercontent.com/37456432/40159700-2a273a3c-59b3-11e8-9223-663575bd62a5.jpg)
What should i do for solve this? Please help me with this problem.

**Comment by canguruhh** [comment]
Have you done another transaction before (sometimes it can take a minute to sync the previous transaction)?

**Comment by canguruhh** [comment]
Can you please press F12 (open development tools) and select the Network tab. On send you should see a broadcast api call. Maybe the response message can help identify the problem.
![image](https://user-images.githubusercontent.com/21195529/40170999-5d0e2e30-59ca-11e8-9683-c3602e7b37ee.png)

**Comment by Attick** [comment]
![viber image](https://user-images.githubusercontent.com/37456432/40171630-843ce2ee-59d4-11e8-82cb-988c7350ca04.jpg)
it's photo myetpwallet on pc, when i press F12 nothing happen

**Comment by canguruhh** [comment]
please use chrome

**Comment by canguruhh** [comment]
just use the same one as you use with the other browser

**Comment by Attick** [comment]
i created it in opera and i didnt open it anywhere. I dont remember about file when i was created  wallet

**Comment by canguruhh** [comment]
but you have the backup words?

**Comment by canguruhh** [comment]
the problem could be that you have too many small inputs. please try to create a smaller transactions and see if that works. you can also just send it to yourself to check.

**Comment by Attick** [comment]
no, i cant find them. can i reestablish them use email? yes, inputs is small becouse they come from miningpool

**Comment by Attick** [comment]
i coud sent 500 etp in one transaction, thenks a lot for advice!!!! and I should create new wallet becouse i cant find recovery words or file on my pc

**Comment by Attick** [comment]
can you tell me how is name file? i try find it on pc

**Comment by canguruhh** [comment]
The default filename is mvs_keystore.json
