### ISSUE TITLE
Same seed phrase, different addresses

### ISSUE THREAD

**Issue by be1box** [mvs-org/lightwallet#117]
I restored my seed phrase at different devices, but I see different addresses, what can be a problem?

**Comment by be1box** [comment]
I tried several times, but only at XiaoMI RedMi 4A I see wrong addresses.

**Comment by be1box** [comment]
Wrong address at XiaoMI:
![2018-05-26 14 36 25](https://user-images.githubusercontent.com/323650/40575685-376f1eb2-60f2-11e8-9873-18ec8c1a9cc9.jpg)

Right address:
![screenshot_20180525-214504_myetpwallet](https://user-images.githubusercontent.com/323650/40575695-74257cb6-60f2-11e8-8382-c00648b62531.jpg)

**Comment by canguruhh** [comment]
there was no change in the wallet generation code. please try again. the wallet does currently not complain about entering non-wordlist words. maybe there was a little spelling difference.

**Comment by canguruhh** [comment]
if you use the textarea you can also copy the text and paste it on the other device to make sure they match

**Comment by be1box** [comment]
There is no difference, I tried several times, at mobile app and at browser.

**Comment by canguruhh** [comment]
whats the result when you enter the words on the browser app?

**Comment by canguruhh** [comment]
use the phone and visit app.myetpwallet.com. then use restore from backup words

**Comment by be1box** [comment]
I think problem with Xiaomi, I copy pasted this phrase. Same addresses at my notebook and Galaxy S8, but different at Xiaomi!

**Comment by canguruhh** [comment]
did you install the app from play store?

**Comment by be1box** [comment]
of course, same problem at web browser.

**Comment by be1box** [comment]
I can make a video if you want :)

**Comment by be1box** [comment]
I figured out this problem. Its ok when I scan QR code from web-wallet, but I import seed phrase I see different phrases.

**Comment by canguruhh** [comment]
Have you tried other mnemonics as well? Maybe you could try to generate one or two new wallets and enter the mnemonics. It is still a mystery to me.
