### ISSUE TITLE
WALLET SYNC

### ISSUE THREAD

**Issue by OzJae** [mvs-org/lightwallet#118]
The blockchain is useless at the moment because no one can access it the wallet sync issue needs to be fixed before anything, the main net has not been launched yet and is not live because it doesn’t work

**Comment by canguruhh** [comment]
There are some wallets having this issue. Obviously not all as the explorer and the lightwallet are working just fine. Mainnet has been launched more than one year ago. Problem of why some wallet run into the sync issue has been identified and fixed for next wallet version which will be released very soon. If you resync your blockchain it will fix your problem (it will take some time to resync blocks). Or just use the lightwallet.
