### ISSUE TITLE
Let user define custom transaction fee 

### ISSUE THREAD

**Issue by betachen** [mvs-org/lightwallet#130]

**Comment by canguruhh** [comment]
Enable the user to choose the transaction fee using a slider. This can be hidden by default in the advanced section.

**Comment by canguruhh** [comment]
This option only applies to transaction types that doesn't have a fixed fee (Avatar and MST registration).

**Comment by LaurentSalou** [comment]
Added under the Advanced options, for transfer (ETP or MST), deposit, create MIT and transfer MIT
It's a slider from 0.0001 to 0.1 ETP
