### ISSUE TITLE
Brief information about MST, MIT, Avatar

### ISSUE THREAD

**Issue by vorapoap** [mvs-org/lightwallet#134]
On listing page of each entity, I believe it would be very nice if there is a brief description describing what are MST, MIT, AVATAR on Metaverse.

**Comment by vorapoap** [comment]
Thanks for the update, I just want to know if the language is not yet translated, does it use the English language one?

**Comment by LaurentSalou** [comment]
Yes if the translation is missing, it automatically falls back on English language
