### ISSUE TITLE
Allow linebreaks on Avatar form message text

### ISSUE THREAD

**Issue by canguruhh** [mvs-org/lightwallet#135]
![image](https://user-images.githubusercontent.com/21195529/42503041-deb1ec46-8437-11e8-9056-6886c6aea688.png)

**Comment by LaurentSalou** [comment]
fixed in fb56c30

![image](https://user-images.githubusercontent.com/29446660/42689110-a44bf30c-86d1-11e8-99a9-d9dff0e33bf2.png)
