### ISSUE TITLE
Let user choose Avatar and MST registration fee

### ISSUE THREAD

**Issue by canguruhh** [mvs-org/lightwallet#136]
Avatar and MST registration fee should be shared between the miners and the foundation as defined by the user. User can choose to give 0 to 0.99% of the fee to the foundation. Minimum transaction fee must always be guaranteed for the miner.

**Comment by canguruhh** [comment]
MetaverseJS lib has been updated. Version 0.3.33 supports to set the bounty fee as the last parameter for avatar and mst issue

**Comment by LaurentSalou** [comment]
Added in 23ba69f
Can choose from 0 to 80% of the fee to the developer-community avatar
