### ISSUE TITLE
Sending an MST make it disappear

### ISSUE THREAD

**Issue by LaurentSalou** [mvs-org/lightwallet#149]
When sending a MST to another account, it disappears from the wallet
User needs to do a Force resynch or way the transaction to be processed to have it back

I suspect it happens when the account only has 1 input for this MST

**Comment by canguruhh** [comment]
Balance gets calculated from utxo. If we want to keep showing spent MST we should add them to the users default assets.

**Comment by canguruhh** [comment]
I changed the handling for new transactions. Most cases are covered now so that all common transaction outputs get calculated.

**Comment by canguruhh** [comment]
Now the asset will still disappear from the list but only if 
- the users balance of that asset is 0
- the asset in not a default asset

Handling for this case will be implemented in #155
