### ISSUE TITLE
Airdrop function

### ISSUE THREAD

**Issue by LaurentSalou** [mvs-org/lightwallet#152]
Add a function to do airdrops of a MST

Based on the ETP balance, gives the option to:
- sent to the top holders (i.e. the 10 000 richest addresses)
- sent to all the addresses with a balance above a threshold (i.e. all the address with more than 10 ETP)

The distribution can be linear (sent X token to each address) or proportional to the ETP balance

Before confirmation, the result can be exported to a CSV file.
After confirmation, the list is split into transactions of 1 000 outputs, and broadcast 1 by 1

**Comment by canguruhh** [comment]
Do we still need this function?

**Comment by LaurentSalou** [comment]
Probably not needed, it is already possible to send to 1000 recipients at once using CSV file
If we really need this function, it can also be outside of the lightwallet, and the lightwallet would be used only to sign the transaction
