### ISSUE TITLE
Add frozen balance value estimation

### ISSUE THREAD

**Issue by LaurentSalou** [mvs-org/lightwallet#161]
We could add the USD balance for both Available and Frozen balances, if there is enough space
Currently it is only displayed for the total

**Comment by canguruhh** [comment]
Especially on phones the space is very limited. Maybe we can make the detailed value estimation optional and allow the user to activate it from the settings menu

**Comment by Stidnoob** [comment]
Having FIAT values on both available balance and frozen balance would be a major quality of life improvement.. allowing people to know at a glance how much they have currently available to spend instead of having to manually calculate it every time

**Comment by LaurentSalou** [comment]
I updated it to the following, please let me know if you have any suggestion!
![screenshot from 2018-08-14 19-07-59](https://user-images.githubusercontent.com/29446660/44088438-ad301862-9ff5-11e8-87a6-7ff6774fd479.png)

**Comment by Stidnoob** [comment]
My only question is when will this be available as an update on Google Play store... Not to rush, but simply curiosity

**Comment by canguruhh** [comment]
Please change the spaces to be a fixed width. The space it too wide on some resolutions.
![image](https://user-images.githubusercontent.com/21195529/44707275-59a2cc80-aaa4-11e8-9bf7-ed448df5907d.png)

**Comment by LaurentSalou** [comment]
Updated as below:
![screenshot from 2018-08-29 18-24-32](https://user-images.githubusercontent.com/29446660/44782243-29991d80-abb9-11e8-924a-5d6fc4d85104.png)

@Stidnoob : the next release (v0.5.1) is planned for middle of September
