### ISSUE TITLE
BALANCE FROZEN

### ISSUE THREAD

**Issue by stanly251** [mvs-org/lightwallet#170]
When I open with a light purse and an official wallet, I do not see a frozen balance. This is only visible in transactions. I do not even see the addresses on which the tokens were frozen. Thanks for your help

**Comment by canguruhh** [comment]
If you click on receive you should see a list of your addresses and also the available and frozen amount of etp for the addresses. On the account page you should have the sum of all frozen etp. If not you might have to clear your cache and try to resync your wallet (settings -> force resync)

**Comment by stanly251** [comment]
Good day. did not help or renew the wallet. I do not see the addresses I
froze in the address list. only in transactions. There is no deposit
history.


po 27. 8. 2018 o 13:43 Sven <notifications@github.com> napísal(a):
