### ISSUE TITLE
I can't send my csd coin to another wallet

### ISSUE THREAD

**Issue by joeyyeo** [mvs-org/lightwallet#177]
when I want to send 20000 csd coin to another wallet，but the display on my phone is
Oops
Unable to create transaction

ERR_INSUFFICIENT_UTXO
why?why i cant'send my csd coin
Please reply as soon as possible,Thank you

**Comment by joeyyeo** [comment]
I just tried the force resync but it still display
Oops
Unable to create transaction

ERR_INSUFFICIENT_UTXO
Pls help me.Thank you
My csd wallet is:MUcFrkgCqF3WZfNNsQ1CLWL2xDPSztVeJF

The csd wallet that I want to send my csd is:MMu2jcEnz7iWNSS5949tX3FVXANz8cDmcb

**Comment by canguruhh** [comment]
Which wallet version do you use. In case you use the browser version please try to clear all your caches or try a different browser.

**Comment by LaurentSalou** [comment]
I see in the explorer this address has CSD but no ETP, maybe you don't have ETP to pay for the transaction fee?
Can you try to do it from your computer, or send a little bit of ETP to this address to pay the transaction fee (0.0001 ETP)?

**Comment by joeyyeo** [comment]
I just send my csd to other wallet,Thanks for your help.
