### ISSUE TITLE
METATIP  Logo on MYETPWALLET 

### ISSUE THREAD

**Issue by dennis45** [mvs-org/lightwallet#183]
Hi, Metatip has being listed on instantbitex and many more to come. Our team wishes Metaverse team to support by listing the logo on myetpwallet front page.

Below are the logo we wishes to attach.

![photo532578084054639194](https://user-images.githubusercontent.com/40360384/46883863-ccfe7300-ce85-11e8-9ebb-420fad587430.jpg)

Transparent
![2018-10-13 01 19 23](https://user-images.githubusercontent.com/40360384/46883963-164ec280-ce86-11e8-8ef6-6d03c2c8db12.jpg)

**Comment by LaurentSalou** [comment]
Hi Dennis!
META's logo is already present in current version, but the balance only display if the account received at least once in its history some META
![screenshot from 2018-10-24 18-28-26](https://user-images.githubusercontent.com/29446660/47424627-a102bc00-d7ba-11e8-9586-075dcbafe96e.png)
