### ISSUE TITLE
Show message if user already signed a multisignature tx

### ISSUE THREAD

**Issue by canguruhh** [mvs-org/lightwallet#187]
If a user enters a transaction that already contains the users signature during the multisig signing process there should be a message to indicate why no additional signature was added to the transaction.
![image](https://user-images.githubusercontent.com/21195529/47218232-598bc280-d3ab-11e8-8b16-086967c04cb3.png)

**Comment by LaurentSalou** [comment]
Error handling added when the user try to sign a transaction he already signed (commit f459de4)
The displayed message is as below:
![screenshot from 2018-10-23 17-51-30](https://user-images.githubusercontent.com/29446660/47352406-66cae900-d6ec-11e8-924a-47dec88c6ba4.png)
