### ISSUE TITLE
Save account settings of browser session for future logins

### ISSUE THREAD

**Issue by canguruhh** [mvs-org/lightwallet#188]
There should also be an option for browser users to save the encrypted account settings for easier future logins just like the mobile version does

**Comment by LaurentSalou** [comment]
Added in 0ea33db
The user has the choice to save the account information or not when he logout. If he choose the save it, a account name will be asked
So far, the information stored are:
- encrypted seed
- index (number of addresses)
- multi-signature addresses
- multi-signature addresses information
- plugins
