### ISSUE TITLE
Connect phone page needs more explanation 

### ISSUE THREAD

**Issue by canguruhh** [mvs-org/lightwallet#19]
maybe 3 pictures that show the sync process

**Comment by LaurentSalou** [comment]
There is 2 parts:
1: On the desktop version, ask to download the App MyETPWallet
2: On the phone, explain the process (On the computer, go to Settings > Connect phone > Show QR Code)

**Comment by canguruhh** [comment]
Thats correct. The desktop notice should focus on security as the private key gets exported. The mobile version should focus on how to connect.

**Comment by atinaaaa** [comment]
**Desktop version text**

Exporting private key to your phone 
1.The data is encrypted in private key and could access into your phone via exporting it.（Scan QR code or input them manually)
2.Please logout the app if you switch your phones. 

How to export private key?(will be displayed by three images with text below)
1.open light wallet on desktop and go to setting.
2.open light wallet app on your phone.
3.scan QR code to enter wallet on your phone.

**Mobile App Version**
text displays on the pre-page of scanning QR code
How to enter your wallet by scanning QR code?
1. Please open wallet on desktop and go to setting page
2. Scan QR code and enter to your wallet by phone

**Comment by canguruhh** [comment]
Maybe we should describe the process incl the pictures also on the phone. If you start the app the first time you might have no idea how to start.

**Comment by atinaaaa** [comment]
So you would like to put a mobile landing page to show how to login?

**Comment by canguruhh** [comment]
Not the landing page. After the user chose the first menu option "Open wallet from qr code"
