### ISSUE TITLE
Specify the network in account object 

### ISSUE THREAD

**Issue by LaurentSalou** [mvs-org/lightwallet#191]
The accounts should contain the network (testnet/mainnet), set when logout, and be displayed only if it matches its network on the login page

**Comment by canguruhh** [comment]
What is the status of this issue?

**Comment by canguruhh** [comment]
Optional property of the account object. It set the login page should hide the account if the network does not match

**Comment by LaurentSalou** [comment]
Done in 6581423
If the network in unknown (existing account till they logout), the account will appear on mainnet only
