### ISSUE TITLE
Multisig wallet should not contain multiple times the same key

### ISSUE THREAD

**Issue by canguruhh** [mvs-org/lightwallet#192]
It seems to be possible to enter the same public key when creating a multisignature wallet

![image](https://user-images.githubusercontent.com/21195529/47470737-54919d80-d807-11e8-9881-2a743c2333b5.png)

**Comment by canguruhh** [comment]
@LaurentSalou please check the status of this issue

**Comment by LaurentSalou** [comment]
Done in 0e5e768
I added 2 checks:
- verify the own public key is not added a second time
- verify an identical public key is not added 2 times
