### ISSUE TITLE
Plugin warning should be on separate page instead of popup

### ISSUE THREAD

**Issue by canguruhh** [mvs-org/lightwallet#196]
For the plugin settings and plugin loads the warning text should be on a separate page instead of the popup. If we decide to use a popup then the plugin load needs to wait until the popup has been closed.

![image](https://user-images.githubusercontent.com/21195529/47471400-5315a480-d80a-11e8-8194-d706a0a2e392.png)

**Comment by LaurentSalou** [comment]
A new page has been added before entering a plugin (commit a5a096d)
