### ISSUE TITLE
Feature Request: Account Statement + Transaction Sheet for MSTs

### ISSUE THREAD

**Issue by CaptainStevey** [mvs-org/lightwallet#198]
Would it be feasible to have an account Statement + transaction Sheet so you can better see your incoming and outgoing as well as total balance?  Basically the same as logging into your bank account.

You should be able to see a top level balance for all your ETP MST wallets and then have the ability to filter for each wallet or a subset of wallets

**Comment by canguruhh** [comment]
Maybe we can implement this feature by enhancing the transaction history items. They can show a list of balance changes that each transaction did. Final balance can be added to the top of the page.

From the receive page we can add a link from the addresses list to the history page that filters the transactions by only the ones of the address.

**Comment by LaurentSalou** [comment]
Added in 28c139c
You will now have the option to filter per MST or address in the history page
Instead of the tx hash, you also now have the amount sent or received (+10 ETP,...)
