### ISSUE TITLE
Not synchronized online wallet. The balance on the wallet is not displayed.

### ISSUE THREAD

**Issue by V81** [mvs-org/lightwallet#202]
Not synchronized online wallet. The balance on the wallet is not displayed.

**Comment by V81** [comment]
`[URL=https://savepice.ru][IMG]https://cdn1.savepice.ru/uploads/2018/12/1/486ee11504824e55d5a48f047f1e8b0e-full.jpg[/IMG][/URL] [URL=https://savepice.ru/upload-image/]upload image[/URL]`

**Comment by V81** [comment]
<a href="https://savepice.ru" target="_blank" title="хостинг картинок"><img src="https://cdn1.savepice.ru/uploads/2018/12/1/486ee11504824e55d5a48f047f1e8b0e-full.jpg" border="0"/></a>

**Comment by V81** [comment]
Transactions are here: https://explorer.mvs.org/adr/MNWiMkC9N8LtsfHFdj9VKbRXxosFVv7UtQ

**Comment by canguruhh** [comment]
Please check your internet connection. Services are running and I can't reproduce the issue.

**Comment by V81** [comment]
the Internet is

**Comment by V81** [comment]
everything in the mobile phone displays

**Comment by V81** [comment]
in the mobile phone displays balance

**Comment by canguruhh** [comment]
also cannot reproduce the issue on browser app. please reset your browser cache and see if the issue persists.

**Comment by V81** [comment]
I cleaned the cache, the problem did not disappear

**Comment by V81** [comment]
Reinstalled the browser, the problem was solved.

**Comment by canguruhh** [comment]
nice
