### ISSUE TITLE
QR Code Scanner Function in light wallet cannot be clicked via web browser.

### ISSUE THREAD

**Issue by pattsoi** [mvs-org/lightwallet#206]
Issue Description: When use mobile browser to import light wallet,  the QR code scanner cannot be opened after click for further process (Both in Safari and Chrome). 
Please review the screen below for your reference.
Issue Category: Bug
Severity: Moderate
Attachment:
![issue206](https://user-images.githubusercontent.com/44576594/50504172-b809a700-0aa6-11e9-8287-760a22261cfa.jpeg)

**Comment by canguruhh** [comment]
thanks for reporting. we will remove the "open from qr code" and "how to import" button for mobile browsers.

**Comment by pattsoi** [comment]
Thanks for your reply. Is it the temporary handling for short-term period?

**Comment by canguruhh** [comment]
we have no access to the qr code scanner from the browser. import from backup words should work.

**Comment by LaurentSalou** [comment]
Indeed I will remove the open from Qrcode and how to import button for users using mobile browser. I will also add the app download buttons instead to suggest to download the app, which is much more adapted to mobile usage

**Comment by LaurentSalou** [comment]
Fixed in 16ed41a
The functions using the qrcode scan have been removed from the web mobile version
