### ISSUE TITLE
Improve recipient address validation

### ISSUE THREAD

**Issue by LaurentSalou** [mvs-org/lightwallet#207]
Currently the validAddress function that check if the recipient address is valid only check the length and the first character of the address to define if it is a valid address.

If the recipient address contains a non-base 58 character (i.e. a small case L), it will be displayed as valid but the transaction generation will fail with an error "Non-base58 character"

If all the characters are valid but the address is not, then the transaction generation will fail with an error "Invalid checksum"

Those 2 errors could be avoid by displaying the address as invalid via validAddress in mvs-service

**Comment by canguruhh** [comment]
Add checksum validation to MetaverseJS
