### ISSUE TITLE
Please wait... Can not send ETP to RightBTC

### ISSUE THREAD

**Issue by ste13fan** [mvs-org/lightwallet#210]
When I click the send button, nothing happens but the message "Please wait…"
I've already tested 3 different Browsers. Also on a different computer.
Please help me.

**Comment by canguruhh** [comment]
Is it possible that your transaction contains a lot of small inputs? Please try a different amount. It would also be good to get some more details about the ETP you want to send. If you dont want to disclose it here you can contact us on discord.

**Comment by canguruhh** [comment]
In case of a wrong password there would be an error message

**Comment by SummerTiger** [comment]
no, it will not give any error message when sending

canguruhh <notifications@github.com> 于 2019年2月20日周三 04:15写道：

**Comment by canguruhh** [comment]
Can you try to send a smaller amount?

**Comment by canguruhh** [comment]
It is very hard to find the problem without any information on the source inputs of the transaction

**Comment by canguruhh** [comment]
There was indeed a problem with a node that was not updated to the latest version. Please check again if you can connect to the network. I did some successful tests.

**Comment by IedSupo** [comment]
same here... sending 761 etp and nothing but "Please wait" for a few days now.. tried different browsers etc

**Comment by ste13fan** [comment]
Thank you canguruhh! It's very simple. Send max. 200 ETP at once and it will work fine.
