### ISSUE TITLE
Only show deposit request if waiting for deposit

### ISSUE THREAD

**Issue by canguruhh** [mvs-org/lightwallet#218]
Only show the request to deposit if the order is in status wait_deposit_send

<img width="490" alt="Screenshot 2019-05-05 at 13 48 48" src="https://user-images.githubusercontent.com/21195529/57193548-a5afe600-6f3c-11e9-9abd-a04c5162672f.png">

**Comment by canguruhh** [comment]
Maybe we can even show a message that the user should not send any funds to that address if the order is in any other status

**Comment by LaurentSalou** [comment]
Added a condition to only display the message if the status is wait_deposit_send, in commit c8b0a52
