### ISSUE TITLE
All content should be visible on mobile view

### ISSUE THREAD

**Issue by canguruhh** [mvs-org/lightwallet#219]
<img width="430" alt="Screenshot 2019-05-05 at 13 52 47" src="https://user-images.githubusercontent.com/21195529/57193614-3981b200-6f3d-11e9-8306-725e026b26d4.png">

**Comment by canguruhh** [comment]
The problem also affects the history list

**Comment by LaurentSalou** [comment]
Display of the etp bridge and etp bridge details pages has been improved in bfcf7ef
