### ISSUE TITLE
Add warning to SWFT support link

### ISSUE THREAD

**Issue by canguruhh** [mvs-org/lightwallet#224]
There should be a warning that the SWFT telegram support will never ask a user to send any funds to addresses other than the deposit address of the order details. Details about the order should not be necessary. The order id should be enough information for the support to find the order.

**Comment by canguruhh** [comment]
the warning is not clear enough. it should be highlighted in some way
<img width="1375" alt="Screenshot 2019-08-28 at 16 34 04" src="https://user-images.githubusercontent.com/21195529/63865508-fcd93b00-c9b1-11e9-8a62-28eb05dc4c7a.png">

**Comment by LaurentSalou** [comment]
Changed to red in 8f1ed5b
