### ISSUE TITLE
Add a network parameter on login page

### ISSUE THREAD

**Issue by LaurentSalou** [mvs-org/lightwallet#242]
The login page should have a parameter to define the default network, so if we want to provide a link to use testnet, we can add this parameter to have the network directly set to testnet when entering the page

**Comment by canguruhh** [comment]
Added query parameter check on the app level. Needs to be tested but it should work now on any page. Not only login.

**Comment by canguruhh** [comment]
@LaurentSalou please test it

**Comment by LaurentSalou** [comment]
tested and works good!
