### ISSUE TITLE
Send page should have an option to add messages

### ISSUE THREAD

**Issue by canguruhh** [mvs-org/lightwallet#25]

**Comment by canguruhh** [comment]
We just need one more optional field to specify a transaction memo.

**Comment by canguruhh** [comment]
Deposit page will also have a message option. For now only one message is possible.

**Comment by LaurentSalou** [comment]
Done for Send (6ddc5ad), SendMore (e5400bb) and Deposit (ae0147c)
The size of the message is checked and a message displayed if too long (9f67037)
