### ISSUE TITLE
Manual request code entry field should be a textarea with enough lines

### ISSUE THREAD

**Issue by canguruhh** [mvs-org/lightwallet#255]
Only a small part of the code is currently visible. Also maybe the form can have some more space to the help button.

<img width="581" alt="Screenshot 2019-08-28 at 19 43 56" src="https://user-images.githubusercontent.com/21195529/63879691-8138b780-c9cc-11e9-98df-a420b61e486d.png">

**Comment by LaurentSalou** [comment]
Done in 62d085b
