### ISSUE TITLE
Error message when trying to sign a multisig transaction should be more precise

### ISSUE THREAD

**Issue by canguruhh** [mvs-org/lightwallet#256]
If the wallet tries to decode and sign a transaction with an input that is not known to the wallet the resulting error message is very general. We should try to identify the actual problem (if its the decoding or data issue).

<img width="916" alt="WechatIMG410" src="https://user-images.githubusercontent.com/21195529/63881305-d924ed80-c9cf-11e9-8603-1febbf749b1d.png">

**Comment by canguruhh** [comment]
Not so important right now so scheduled for next release

**Comment by LaurentSalou** [comment]
Changed in 1062ff9
Now the confirm-tx page fully support multisig transactions
