### ISSUE TITLE
Raw transaction signing should handle partial signing

### ISSUE THREAD

**Issue by canguruhh** [mvs-org/lightwallet#258]
Seems like the wallet rejects transaction with inputs that are unknown to the wallet. If there are unknown inputs it should be possible to only sign the inputs that are known and belong to the wallet

**Comment by canguruhh** [comment]
Added a new parameter to the [MetaverseJS](https://github.com/canguruhh/metaversejs) wallet sign function. Providing false as the 2nd parameter will prevent the function from throwing an error if the address cannot be found in the wallet. Handle with care. Should only be used for partial signing and let the user know its a partial sign.

**Comment by LaurentSalou** [comment]
Done in a042b4b
