### ISSUE TITLE
Limit the number of inputs per transaction

### ISSUE THREAD

**Issue by LaurentSalou** [mvs-org/lightwallet#264]
A transaction can only contain a limited number of inputs, a message should be displayed if it has more inputs. The message should recommend to first spend a smaller amount in order to have less inputs

**Comment by canguruhh** [comment]
lets try the regular coinselect and in case it would select too many utxo we do a 2nd run that prefers large utxo. if it is still too many then show an error message

**Comment by LaurentSalou** [comment]
Added to metaversejs v0.3.80
