### ISSUE TITLE
Problem loading plugin from localhost

### ISSUE THREAD

**Issue by canguruhh** [mvs-org/lightwallet#267]
Tried to open a plugin from localhost using the config from https://hello-world.blocktrack.net/config.json

<img width="571" alt="Screenshot 2019-09-19 at 12 58 07" src="https://user-images.githubusercontent.com/21195529/65214680-59290980-dadd-11e9-885e-ad2c210ed8bb.png">

**Comment by LaurentSalou** [comment]
Mesage changed in b862b7b
Previously, the first check was to check the name, and if failed was showing this error. Now there is an additional check right before to make sure the plugins info exist, and then it check the name
