### ISSUE TITLE
MST creation problem

### ISSUE THREAD

**Issue by canguruhh** [mvs-org/lightwallet#279]
<img width="1508" alt="Screenshot 2019-11-13 at 12 25 01" src="https://user-images.githubusercontent.com/21195529/68788134-dae67080-0610-11ea-8fa5-914345a1aa96.png">

**Comment by LaurentSalou** [comment]
Fixed in MetaverseJS
https://github.com/canguruhh/metaversejs/commit/293e252f529a449ef7c7f898c26dfb5113965cf7
