### ISSUE TITLE
hello help help back up problem 

### ISSUE THREAD

**Issue by iAdam87** [mvs-org/lightwallet#280]
**i create my wallet mobile etp  2018/8 and i take 24 words backup and send to my gmail   every few days i just check my wallet and see my balance when try to send etp i just type my password 

but 2 days ago for first time i open my etp app on my mobile and he ask me for backup to sign in i chose words back up and try its not working i swear its my back up words i just copy and send to gmail  2018/8

sorry for my bad english**

**Comment by canguruhh** [comment]
@iAdam87  please let us know if the issue is resolved and how you resolved it. it would help us to improve our support. thanks

**Comment by iAdam87** [comment]
i just open my wallet on my mobile 2 hrs ago its open normal like every day without ask for backup  and i send my etp to bitfinex and i will create new wallet and download backup file on my pc cuz my 24 word still not working for old wallet i was very sad but now i am happy

**Comment by canguruhh** [comment]
great that it worked. after sending your funds to a new wallet it would be nice if you could send me your old not working mnemonic so that i can try to find out what was causing the issue. you can use the create issue function in the wallet to send the message privately

**Comment by iAdam87** [comment]
ye i can  send u here or where ?

**Comment by canguruhh** [comment]
you can send here or if you want to want to send privately you can also use the report bug option in the wallet

**Comment by iAdam87** [comment]
ok i will now send report bug option and say message to canguruhh

**Comment by iAdam87** [comment]
look this my 24 words

 sight grid tired trash only modify august crack review stone stick galaxy myself garage easy change stock caught call edge put candy stock nerve

**Comment by iAdam87** [comment]
anyway wallet balance 0  and i will not use this old wallet again  i have new wallet

**Comment by canguruhh** [comment]
thanks. did you create the wallet on a phone app or in your browser?

**Comment by iAdam87** [comment]
this 24 word create by mobile 1 yr ago   but  new wallet create by web pc and its working too on mobile i test it
