### ISSUE TITLE
Send page should show the value in base currency 

### ISSUE THREAD

**Issue by canguruhh** [mvs-org/lightwallet#285]
On the send page there should ba a little info text after the amount field to indicate the value of the amount in the users base currency

**Comment by LaurentSalou** [comment]
Added in 42ddfe6

![Screenshot from 2020-01-16 19-22-42](https://user-images.githubusercontent.com/29446660/72590504-d43de780-3938-11ea-97e0-7e8cfec8dd3e.png)
