### ISSUE TITLE
sync failure so many times when importing account.

### ISSUE THREAD

**Issue by aaronzhzh** [mvs-org/lightwallet#288]
when importing the account which has many transactions(including POS mining) , lightwallet sync occurs error . the error will appear for many times  , click "retry" button cannot solve the problem until reboot the app and continue to sync.

**Comment by canguruhh** [comment]
accounts with a lot of transactions which is usually the case for miners are not supported and will unlikely be supported in the near future because of compatibility issues with the browser version.

**Comment by aaronzhzh** [comment]
thanks for replying and here is another question: how about adding notification function to lightwallet when receive the transactions? thank you.

**Comment by canguruhh** [comment]
can you please try to sync again? from which location do you try to sync? we do plan to support notifications at some point
