### ISSUE TITLE
Default fee should be suggested by explorer

### ISSUE THREAD

**Issue by canguruhh** [mvs-org/lightwallet#290]
Unless the user selects the advanced options to set a fee it should try to ask the explorer for a fee suggestion.

**Comment by canguruhh** [comment]
@LaurentSalou Is this working on the ionic 5 version?

**Comment by LaurentSalou** [comment]
checked and tested on the ionic 5 version, it works as expected (but so far all the fees from the explorer are set to the minimum so it has no effect on mainnet)
