### ISSUE TITLE
Mining rewards are added to transactions before mining freeze time completed

### ISSUE THREAD

**Issue by aaronzhzh** [mvs-org/lightwallet#296]
lightwallet version iOS 0.8.14  
an error occurred "validate transaction failure: validation of inputs failed" when i need to send etp to the other addresses or avatars. 
resync the lightwallet still doesn't work.

besides, my fullnode wallet is working on pos mining.will it cause this problem? or something else.

**Comment by aaronzhzh** [comment]
![d4b2fb8d05d59385f9393880941bb2c](https://user-images.githubusercontent.com/61041995/76400033-9b5f4380-63ba-11ea-8a43-9495a469efa5.jpg)

**Comment by canguruhh** [comment]
hi. i need more information. is it possible for you to open the advanced section and send me the signed hex encoded raw transaction to sven.mutzl@viewfin.com? all systems seem to work fine but we do know that there can be some problems with wallets that have a lot of transactions (mostly miners).

**Comment by aaronzhzh** [comment]
okay

**Comment by aaronzhzh** [comment]
email sent.

**Comment by canguruhh** [comment]
ok. we identified the problem. it happens because the wallet is trying to spend a mining reward that has not yet reached its lock. the fullnode should indicate that it is not spendable. we will implement the same behaviour for the explorer and lightwallet asap. keep you updated

**Comment by canguruhh** [comment]
It should be fixed now. The wallet now detects newly mined ETP and freezes it for 1000 block (~6h). It should calculate and show you the available balance.
