### ISSUE TITLE
Should be able to copy the transaction hash after sending

### ISSUE THREAD

**Issue by LaurentSalou** [mvs-org/lightwallet#30]
Add a button "Copy transaction hash" in the pop-up opened after sending a transaction or a deposit.

**Comment by canguruhh** [comment]
Any idea how to do that? We might need a new handling after the broadcast.

**Comment by LaurentSalou** [comment]
I just added a "Copy" button in the AlertController, with the ionic-native/clipboard module.
However, this module only works on mobile device. If we want to add something similar on desktop, we will need to find another way to display the transaction hash (i.e. opening a new page "Transaction complete" instead of an alert)

**Comment by canguruhh** [comment]
Yes ok. I thought that we could show the pending transaction at the top of the account page until the transaction has been synced. To indicate that there is a pending transaction because you cant create multiple transactions yet.
