### ISSUE TITLE
Wallet issue

### ISSUE THREAD

**Issue by michaeldab** [mvs-org/lightwallet#335]
When the update rolled out on the desktop wallet, I logged in to the new system and my funds were gone.

Where did they go and how do i regain access to them?

They were bought in 2017.

Thanks

**Comment by canguruhh** [comment]
There was no recent update of the desktop wallet. Only the IOS version was updated. If this version causes issues for you please try to import your backup words into one of the other wallets. You can find the official web version on myetpwallet.com.
