### ISSUE TITLE
android phone wallet 

### ISSUE THREAD

**Issue by maxremus** [mvs-org/lightwallet#337]
hello I am writing to you with a request for help my case is the following i have a wallet on android phone but i have not recorded anywhere meta phrase and json file. the phone has restarted and has left the wallet now I can't enter it and transfer the coins that have been withdrawn. is there any other way to verify that the wallet is mine and to transfer the coins to a new wallet. thanks in advance for the reply my wallet is with address MTEp8jXfgte9oku7FyWTdvaoamEEnj2ymJ

**Comment by LaurentSalou** [comment]
Hello, unfortunately the only way to access the wallet is using either the 24 words or the json file with its password
