### ISSUE TITLE
Unable to send my etp 

### ISSUE THREAD

**Issue by Rufus-Ruffcut** [mvs-org/lightwallet#344]
Hello :)

Ihave this issue for about a week, i want to send my etp (doesn''t matter which adres)
and i keep getting  the message: unable to broadcast the transaction unsuccesful http response
i have tried many things but i cant get it right... it occures on the desktop and on the phone, 
even if i make a new etp wallet this message occures

grtz

**Comment by aaronzhzh** [comment]
You can sign the transaction in the lightwallet and copy the hex code to the explorer to broadcast

**Comment by aaronzhzh** [comment]
https://explorer.mvs.org/broadcast

**Comment by canguruhh** [comment]
the problem should be fixed now and it should work without the tx copy trick. thanks @aaronzhzh for the workaround

**Comment by Rufus-Ruffcut** [comment]
now its getting scary :)  where do i find the hex code?

**Comment by canguruhh** [comment]
> now its getting scary :) where do i find the hex code?

you can choose to sign only in the advanced section during the send process.

please just try to do a regular send. it should also work now. the problem was that the node that the lightwallet uses for broadcasting was stuck

**Comment by Rufus-Ruffcut** [comment]
when im sending normal it keeps loading....

**Comment by canguruhh** [comment]
just tried again. its works for me. are you using the lightwallet or which wallet do you use?

**Comment by Rufus-Ruffcut** [comment]
i use my etp wallet on my android

**Comment by Rufus-Ruffcut** [comment]
one time it workt on my phone.....when i try to send more it did not work...it keeps loading

**Comment by canguruhh** [comment]
maybe your wallet it out of sync. try to select settings -> force resync.

i just tried my android test device without issues

**Comment by Rufus-Ruffcut** [comment]
It works! :)
Thanks many time!!! :)

**Comment by canguruhh** [comment]
no problem
