### ISSUE TITLE
Phone should not hide balances while loading

### ISSUE THREAD

**Issue by canguruhh** [mvs-org/lightwallet#39]
On the phone app the initial loading animation should only appear if there are no balances. if there are balances in local storage it should only indicate that the shown balances might not be up to date. maybe a little loading animation at the top. like after the scroll down refresh.

**Comment by LaurentSalou** [comment]
A good way would to use a boolean to define if it's the first loading
If it is, we only display the loading (as currently)
If it's not (= we already have information in the cache), we display the already loaded information and a small loading animation
