### ISSUE TITLE
Instruction how to deploy Light Wallet is needed

### ISSUE THREAD

**Issue by vorapoap** [mvs-org/lightwallet#43]
Instruction how to deploy Light Wallet is needed so others know how to deploy it in their dev environment and start contribution quickly. Probably in README.MD

**Comment by canguruhh** [comment]
Yes sure. Actually the process is very simple on limux and osx. I have no idea how it works for other exotic dev environments. For the current readme i assumed that nodejs and npm are installed. I think that should be all. Rest gets downloaded automatically by ionic. However I can only give linux/osx support.

**Comment by vorapoap** [comment]
Yes... that is enough... I see the change thanks.
