### ISSUE TITLE
Register Light Wallet as browser native app

### ISSUE THREAD

**Issue by vorapoap** [mvs-org/lightwallet#44]
For example, in Chrome eco-system - you can click on the app icon to start abc app.
I think this will create more Light Wallet awareness. The app is installed from the market

Beside that you also get the rating and review to increase popularity

It should be done on both Firefox and Chrome

**Comment by canguruhh** [comment]
Do you have more information on that like link, example...? What do we have to do for that?

**Comment by vorapoap** [comment]
A lot of links to see....  I have never done this yet, but I think it is highly possible

https://www.google.co.th/search?q=ionic+chrome+app
https://forum.ionicframework.com/t/ionic2-web-app-to-chrome-app/62210
https://ionicframework.com/docs/native/in-app-browser/
https://forum.ionicframework.com/t/firefox-desktop-browser/32127

So basicly, you will get Chrome App or Firefox App from Ionic..  I think it will create hype since this is new  to blockchain world.

**Comment by canguruhh** [comment]
@vorapoap finally done on https://chrome.google.com/webstore/detail/myetpwallet/llmhohnalldcdbmbnbjpjnmacbmpolkf
