### ISSUE TITLE
Frozen estimation time

### ISSUE THREAD

**Issue by vorapoap** [mvs-org/lightwallet#47]
It should be nice to show both time estimation next to block height.
The block height alone is not friendly to new comer.

It will be best if the estimation is calculated base on latest mining power.

**Comment by canguruhh** [comment]
Agree. I think we can just take the average blocktime from the last x blocks and multiply it with the number of blocks

**Comment by canguruhh** [comment]
Make sure to let the user know that it is just an approximation

**Comment by LaurentSalou** [comment]
Done in 47d8d30
