### ISSUE TITLE
Unfriendly error message "Could not create the transaction. Please check your input and try again."

### ISSUE THREAD

**Issue by vorapoap** [mvs-org/lightwallet#48]
I got this message when trying to transfer my asset.
Not sure what it means though.
I put the recipient address and password.
What I got is..
"ERROR_SEND_TEXT": "Could not create the transaction. Please check your input and try again."

This is frustrating both to me and to new users.

**Comment by canguruhh** [comment]
Oh yes you are right. We should have more error messages on the send transaction functions. Also for deposit... it should be the same.
For development you should check the js console of the response of the broadcast api call. some testing servers are not up 100%. we change stuff and take them down from time to time. (error 400)

**Comment by canguruhh** [comment]
I added multiple error handing cases. Hope this resolves the issue.
