### ISSUE TITLE
Can't issue Asset with large number of coins

### ISSUE THREAD

**Issue by LaurentSalou** [mvs-org/lightwallet#62]
When we try to issue an Asset with a large number of coins and decimals (i.e. 100M coins with 8 decimals), the creation fail with error:
"RangeError: value out of range"

The creation works fine on the full node wallet with the same parameters

**Comment by canguruhh** [comment]
It is a library issue. I changed the limit in version 0.2.30 of metaversejs. The limit depends on the number of bits. If you have 8 decimals and an amount of 100 million it will be 10^16. Thats a big number but it should work now.
