### ISSUE TITLE
Button reset on "import words" screen changing color after touch.

### ISSUE THREAD

**Issue by PsiHamster** [mvs-org/lightwallet#68]
![ezgif-4-c6a1c88633](https://user-images.githubusercontent.com/8936339/34715053-41667fea-f523-11e7-8800-bc374ba0ec17.gif)
ER: Button changes colour back after release.
AR: Button changes colour to black.

**Comment by LaurentSalou** [comment]
I changed the css to switch to black on :active state instead of :hover
