### ISSUE TITLE
Scrollbar disappears at many screens

### ISSUE THREAD

**Issue by PsiHamster** [mvs-org/lightwallet#69]
![ezgif-4-2eea7925d5](https://user-images.githubusercontent.com/8936339/34715398-7103b35c-f524-11e7-8d19-f8f083526c20.gif)

There is no scrollbar at all screens. It just disappears within a sec.

Device: Xiaomi redmi 4

**Comment by canguruhh** [comment]
Whats the status of this issue?

**Comment by canguruhh** [comment]
closed because of inactivity
