### ISSUE TITLE
You can not be able to change your passphrase after leaving focus from a field.

### ISSUE THREAD

**Issue by PsiHamster** [mvs-org/lightwallet#70]
![ezgif-4-45028f7ca9](https://user-images.githubusercontent.com/8936339/34715995-724f7b4a-f526-11e7-9ea7-1381a86041db.gif)
ER: You can change your password.
AR: You need to go on previous screen and press button again to be able to change password.

Device Xiaomi redmi 4

**Comment by canguruhh** [comment]
That is a strange issue. Maybe we can just add a reset button if the issue is not obvious to fix

**Comment by PsiHamster** [comment]
It works for me in all text fields. So I can not be able to change recipient adress or amount if I just changing typing field...
![ezgif-4-15fde775cf](https://user-images.githubusercontent.com/8936339/34717197-231b631e-f52a-11e7-9b37-5c92f07d2552.gif)

**Comment by canguruhh** [comment]
Hmm. getting stranger. i can edit the textboxes. i guess we need to check other devices

**Comment by canguruhh** [comment]
Can't reproduce
