### ISSUE TITLE
Cannot give access to my camera

### ISSUE THREAD

**Issue by PsiHamster** [mvs-org/lightwallet#71]
![ezgif-4-494beb4cc4 1](https://user-images.githubusercontent.com/8936339/34716546-1205ed1c-f528-11e7-8628-b98992fa7847.gif)

Button that gives access to camera seems like active but when I pressed it nothing changes. (In other applications asking permissions works correctly so maybe problem with your app.)

Device: Xiaomi redmi 4

**Comment by npig** [comment]
No issues on my phone. Pixel

**Comment by canguruhh** [comment]
Looks like there is an incompatibility with your phone. Also the other issue with the input fields might be a result of the same issue. Which android version do you use?

**Comment by PsiHamster** [comment]
xiaomi redmi 4, android 6.0.1, miui 8

**Comment by canguruhh** [comment]
Please try do deactivate your debug mode. I guess that you enabled some settings to record the screen. I hope that it might be related to your settings because we haven't been able to reproduce the problem yet.

**Comment by PsiHamster** [comment]
Yeah. Seems like it was "AZ Screen" application problem... Don't know why the problem only occurred with this application but it works fine without it. So I will close issue.

(But https://github.com/mvs-org/lightwallet/issues/70 still actuall. Checked it without any third-party applications.)
