### ISSUE TITLE
Cannot import my wallet from file 

### ISSUE THREAD

**Issue by PsiHamster** [mvs-org/lightwallet#72]
![opera_2018-01-09_15-46-28](https://user-images.githubusercontent.com/8936339/34717273-6856b5aa-f52a-11e7-82f5-e7c596f68387.png)
There is an error in console when I trying to load from correct file. (On screen just nothing changes)

Browser: Opera.

**Comment by canguruhh** [comment]
Please try chrome or firefox

**Comment by PsiHamster** [comment]
![nvidia share_2018-01-09_15-54-22](https://user-images.githubusercontent.com/8936339/34717572-77522d2c-f52b-11e7-9b0e-f2767f709969.png)
Works correctly in both... And in private browsing mode in opera. Seems like problem in mine extensions.
