### ISSUE TITLE
Wrong title "Show balances for all assets"

### ISSUE THREAD

**Issue by PsiHamster** [mvs-org/lightwallet#73]
When switch is active balances are hidden. So title should be like "Hide balances for all assets". (Or it should be hidden by default and shows only if switch is active)
![firefox_2018-01-09_15-58-57](https://user-images.githubusercontent.com/8936339/34717784-22bcf32c-f52c-11e7-899b-3fc51ea01cc1.png)
![firefox_2018-01-09_15-59-05](https://user-images.githubusercontent.com/8936339/34717785-22e2fa5e-f52c-11e7-888c-a1ff29aec51d.png)

**Comment by canguruhh** [comment]
It happens becuase you dont have any assets. Default is to show the balance of the asset that you have chosen. But if you set the switch it will also show the balances of the other assets.
