### ISSUE TITLE
Extra scrollbar in title of popup menu

### ISSUE THREAD

**Issue by PsiHamster** [mvs-org/lightwallet#74]
![acdseeqvpro10_2018-01-09_16-12-54](https://user-images.githubusercontent.com/8936339/34718316-171c4002-f52e-11e7-9fa5-02669a0d123b.png)
![firefox_2018-01-09_16-14-08](https://user-images.githubusercontent.com/8936339/34718365-440f4cda-f52e-11e7-8395-87d71f2b28f7.png)
![firefox_2018-01-09_16-15-15](https://user-images.githubusercontent.com/8936339/34718396-62549db2-f52e-11e7-83bc-bff65d343d38.png)
It's empty field "alert-message" with scrollbar.

**Comment by LaurentSalou** [comment]
I didn't find a way to reproduce the issue. 

In order to fix this issue and  #69 at the same time, I will remove the default scroll-bar and add a correct one via CSS in a later version
