### ISSUE TITLE
Negative amount numbers marks as good

### ISSUE THREAD

**Issue by PsiHamster** [mvs-org/lightwallet#75]
![firefox_2018-01-09_16-18-17](https://user-images.githubusercontent.com/8936339/34718533-e6feb1a6-f52e-11e7-959a-dbfaa91b3332.png)

ER: Red highlight and cannot to send.
AR: You can try to send negative amount.

**Comment by canguruhh** [comment]
Test for numerical is obviously not enough. If you try to send it it would automatically be rejected but the error handling should already indicate the error.

**Comment by LaurentSalou** [comment]
Done, the rules are:

For ETP:
> 0.0001 (the minimum fee)
has less than 8 decimal
lower or equal to the available amount

For other assets:
> 0
has less decimals than the max number of decimals allowed
lower or equal to the available amount
