### ISSUE TITLE
Scan recipient address by qr code

### ISSUE THREAD

**Issue by canguruhh** [mvs-org/lightwallet#77]
On the mobile send page there should be a scan button to scan the recipient address

**Comment by LaurentSalou** [comment]
Added for both Transfer asset and Deposit pages
I will add additional checks in case the address scanned is wrong

**Comment by LaurentSalou** [comment]
All good now, in Transfer asset and Deposit pages. It will display a popup error if the address scanned is incorrect (check the length and the first character of the address)
