### ISSUE TITLE
Negative display when trying to "send all" on Send menu when you have no ETP in wallet

### ISSUE THREAD

**Issue by raflizo** [mvs-org/lightwallet#80]
![screenshot_20180125-172844](https://user-images.githubusercontent.com/35444207/35399761-53433db4-01f5-11e8-9cae-739641761b91.jpg)

When pushing the button "send all" :
this is probably cause it adds every ETP i have ( 0 )  and it subtracts the fee. but it should say a message like "not enough ETP in wallet" or something

android wallet version: 0.2.1b5

**Comment by raflizo** [comment]
also, the "scan QR button" doesn't do anything when pressed in send menu

**Comment by LaurentSalou** [comment]
Thanks for reporting this! We have just updated it (Version 0.2.1b6)
We removed the Send All button, that we will add back in Version 0.3.1
And the address scanning is correctly working now, you can try it by scanning one of your addresses in "Receive"

**Comment by raflizo** [comment]
i just updated to 0.2.1r1 (the newest one on play store 29 jan 2018) but it doesn't open my camera. I noticed when de-installing and reinstalling it doesn't ask for camera permission. Also when i check the list for permissions, ETP test app isn't even on the list. i use android 8.0.0

**Comment by LaurentSalou** [comment]
sorry the problem came back in this version, 0.2.1r3 is working fine now (the permission is asked when you use the button for the first time)

**Comment by raflizo** [comment]
updated and it works indeed

**Comment by LaurentSalou** [comment]
To come back to the initial issue, the button will only be displayed if the ETP Balance is higher than the transaction fee ( >0.0001 ETP)
