### ISSUE TITLE
Specific Login page for browser on phone

### ISSUE THREAD

**Issue by LaurentSalou** [mvs-org/lightwallet#81]
We need a specific page if the login page is reached from a mobile browser. This page will advise to download the mobile app (Android or IOS)

**Comment by akshaynexus** [comment]
this is already done and shows to download the app when you visit myetpwallet.com

**Comment by LaurentSalou** [comment]
Hi akshaynexus, thanks for your interest in the lightwallet !

Indeed the change is already effective on myetpwallet.com, but I also want to have it on app.myetpwallet.com. Users are not supposed to reach this page from a phone, but it's just in case someone use directly the address app.myetpwallet.com

The change is already done on the branch V0.3.1, we will deploy it in next release
