### ISSUE TITLE
Asset character length restriction, or make it scrollable

### ISSUE THREAD

**Issue by raflizo** [mvs-org/lightwallet#91]
In vertical position on my phone there are 16 characters visible, this is expanded to 30 in horizontal view, but i can't see past the 16 on vertical view. Restrict it, make it scrollable or zoomable. Restricting should be best to be honest.

![screenshot_20180201-224840_01](https://user-images.githubusercontent.com/35444207/35705838-ec04c2bc-07a3-11e8-962d-0b593324828a.jpg)
![screenshot_20180201-225016](https://user-images.githubusercontent.com/35444207/35705839-ec1f1978-07a3-11e8-82ac-95eae50e57ca.jpg)

**Comment by canguruhh** [comment]
Just add ... in the end to indicate that the full symbol can't be displayed. We can't support longer names on all phones. If projects need lightwallet support they should choose a shorter MST symbol or request implementation of special behavior.

**Comment by LaurentSalou** [comment]
Done in 01622df
