### ISSUE TITLE
Multiple pop ups are scrollable but the cancel / ok button aren't

### ISSUE THREAD

**Issue by raflizo** [mvs-org/lightwallet#92]
as seen on this screenshot, i can scroll the addresses but the cancel / ok button do not come into view, so i can't push them in horizontal view.

![screenshot_20180201-225157](https://user-images.githubusercontent.com/35444207/35706033-943fd502-07a4-11e8-8b31-2ad61e776dd8.jpg)

**Comment by LaurentSalou** [comment]
The problem only appears in landscape view
Since landscape view will be disabled from V0.3.1, the issue will not occurs anymore
