### ISSUE TITLE
QR code not scannable in horizontal view

### ISSUE THREAD

**Issue by raflizo** [mvs-org/lightwallet#93]
in receive menu, the QR code isn't scannable in horizontal view, due to automatically resizing to full size. Make it zoomable or restrict it to be able to expand so big ( yet difficult since it's phone size related i think)

![screenshot_20180201-225238](https://user-images.githubusercontent.com/35444207/35706094-c7955bd4-07a4-11e8-86eb-110b56e0a2ba.jpg)

**Comment by LaurentSalou** [comment]
I blocked the orientation to portrait only, since the landscape view bring a few issues and is not useful for the wallet in my opinion
it will be effective from V0.3.1
