### ISSUE TITLE
Adresses not readable in Solarized theme

### ISSUE THREAD

**Issue by raflizo** [mvs-org/lightwallet#94]
Title explains it all i guess, my advice is to use the "transaction fee" color, one click back.

![screenshot_20180201-223952_01](https://user-images.githubusercontent.com/35444207/35706258-5cb78002-07a5-11e8-953c-a99c9ff708c9.jpg)

**Comment by raflizo** [comment]
okay i must say it looks a lot brigher here as on my phone, but still it's better to change the color to something brighter.

**Comment by LaurentSalou** [comment]
It was indeed very difficult to read on phone
I changed the colour to #0f8082 (the same as "Available balance" and "Transaction Fee" fields)
It will be in version 0.3.1
