### ISSUE TITLE
"Connect phone" is not in settings menu

### ISSUE THREAD

**Issue by pjhermes** [mvs-org/lightwallet#98]
I can't connect to my etp wallet via the android app, as there is no connect phone option so I can't get a QR code.
![screenshot_20180207-204123](https://user-images.githubusercontent.com/34345450/35931935-4d3bb476-0c47-11e8-9431-f4b280cce0fb.png)

**Comment by LaurentSalou** [comment]
Clean your cache or use a different browser and you will have the option
When we deploy an update, some info of the previous version stay in the cache, so everything is not updated. We need to find a way to prevent this for the future releases
